### ISSUE TITLE
undefined local variable or method `per_page_default_size' error

### ISSUE THREAD

**Issue by Manidavid** [timoschilling/active_admin_pagination#1]
i have added the **gem 'active_admin_pagination'** in my Gemfile and given the pagination in resource file, but getting the **undefined local variable or method `per_page_default_size'** error.

app/admin/project.rb

```
ActiveAdmin.register Project do
    pagination [10, 50, 100], 50

    controller do
      def scoped_collection
        end_of_association_chain.accessible_by(current_ability)
      end
     end
end
```

**Comment by timoschilling** [comment]
This gem is build for ActiveAdmin 1.0, if you use ActiveAdmin 0.6 you need to fix it by your self, if you use 1.0 update to a ref after activeadmin/activeadmin#3748 is merged.

I will deprecate this gem now.
